version: '3.9'
services:
  pixbi:
    image: pixbi-dotnet7:1.27
    container_name: pixbi
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - net-pixbi

  postgres-db:
      image: postgres:alpine3.19
      container_name: postgres-db
      restart: unless-stopped
      volumes:
        - ./container-data/postgres:/var/lib/postgresql/data
        - /etc/localtime:/etc/localtime:ro
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      expose:
        - "5432"
      networks:
        - net-pixbi

  clickhouse-db:
    image: clickhouse/clickhouse-server
    #user: "101:101"
    container_name: clickhouse-db
    restart: unless-stopped
    #hostname: clickhouse
    volumes:
      - ./container-data/clickhouse/configs:/etc/clickhouse-server
      - ./container-data/clickhouse/main:/var/lib/clickhouse
      - ./container-data/clickhouse/logs:/var/log/clickhouse-server
      - /etc/localtime:/etc/localtime:ro
    environment:
        CLICKHOUSE_USER: ${CLICKHOUSE_USER}
        CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
        CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
#        CLICKHOUSE_UID: 0
#        CLICKHOUSE_GID: 0
    ports:
      - "8123:8123"
      - "9000:9000"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
        - net-pixbi

networks:
  net-pixbi:
